sudo: required # docker를 사용해야하므로
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPT=1 # google cloud sdk가 display하지 않도록 함.
before_install:
  - openssl aes-256-cbc -K $encrypted_7da1215220d9_key -iv $encrypted_7da1215220d9_iv -in service-account.json.enc -out service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null; #google sdk를 설치
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl # update kubectl
  - gcloud auth activate-service-account --key-file service-account.json
  - gcloud config set project mutli-k8s
  - gcloud config set compute/zone asia-northeast1-a
  - gcloud container clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t sangkwun/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run sangkwun/react-test npm test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
